
// Generated By Leetcode2IDE
#include <bits/stdc++.h>
using namespace std;



class Solution {
public:
    bool checkXMatrix(vector<vector<int>>& grid) {
        int n = grid.size();
        for(int i = 0; i < n; i++){
        	for(int j = 0; j < n; j++){
        		if(i == j or (i + j == n - 1)){
        			if(grid[i][j] == 0) return false;
        		}else{
        			if(grid[i][j] != 0) return false;
        		}
        	}
        }
        return true;
    }
};


int main() {

  
  	Solution leetcode2IDE;
	vector<vector<int>> grid1 = {{2,0,0,1},{0,3,1,0},{0,5,2,0},{4,0,0,2}};
	bool output_1 = true;
	if(leetcode2IDE.checkXMatrix(grid1)==output_1){
		cout << "Sample #1 : Accepted" << endl;
	}else{
		cout << "Sample #1 : Wrong Answer" << endl;
	}

	vector<vector<int>> grid2 = {{5,7,0},{0,3,1},{0,5,0}};
	bool output_2 = false;
	if(leetcode2IDE.checkXMatrix(grid2)==output_2){
		cout << "Sample #2 : Accepted" << endl;
	}else{
		cout << "Sample #2 : Wrong Answer" << endl;
	}

	


  return 0;
}
